# Generated by Django 6.0.4 on 2026-04-27 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='Full URL to the file in the storage bucket.', max_length=2000)),
                ('file_name', models.CharField(help_text='Original filename as uploaded by the user or generated by AI.', max_length=500)),
                ('storage_key', models.CharField(blank=True, help_text='Storage backend object key (e.g. S3 key). Used for deletion and refresh.', max_length=1000)),
                ('doc_type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('portfolio', 'Portfolio'), ('other', 'Other')], db_index=True, default='resume', max_length=20)),
                ('is_ai_generated', models.BooleanField(default=False, help_text='True if this document was generated or tailored by Pathfind AI.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('lever', 'Lever'), ('greenhouse', 'Greenhouse'), ('other', 'Other')], db_index=True, default='manual', max_length=20)),
                ('source_url', models.URLField(blank=True, help_text='Original URL of the job posting, if available.', max_length=2000)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('is_remote', models.BooleanField(default=False)),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='Annual salary lower bound (currency assumed from user preference).', null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='Annual salary upper bound.', null=True)),
                ('posted_at', models.DateTimeField(blank=True, help_text='Original posting date from the source, if available.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'job listing',
                'verbose_name_plural': 'job listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'title'], name='jobs_joblis_company_b4bd5a_idx'), models.Index(fields=['source', 'source_url'], name='jobs_joblis_source_bfd14f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('phone_screen', 'Phone Screen'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='saved', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Private notes about this application (interviews, contacts, etc.).')),
                ('applied_at', models.DateTimeField(blank=True, help_text='When the user actually submitted the application.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('cover_letter', models.ForeignKey(blank=True, help_text='Cover letter used for this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_as_cover_letter', to='jobs.document')),
                ('resume', models.ForeignKey(blank=True, help_text='Tailored resume used for this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_as_resume', to='jobs.document')),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joblisting')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='jobs_applic_user_id_dc18c2_idx')],
                'unique_together': {('user', 'job_listing')},
            },
        ),
    ]
