# Generated by Django 6.0.4 on 2026-04-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('adzuna', 'Adzuna'), ('jooble', 'Jooble'), ('careerjet', 'Careerjet'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('lever', 'Lever'), ('greenhouse', 'Greenhouse'), ('other', 'Other')], db_index=True, default='manual', max_length=20),
        ),
    ]
