# Generated by Django 6.0.4 on 2026-04-30 21:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_api_job_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='L2-normalised embedding vector produced by the SBERT model.')),
                ('model_name', models.CharField(default='all-MiniLM-L6-v2', help_text='Identifier of the model used to produce this vector.', max_length=200)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('job_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='jobs.joblisting')),
            ],
            options={
                'verbose_name': 'job embedding',
                'verbose_name_plural': 'job embeddings',
            },
        ),
    ]
