# Generated by Django 6.0.4 on 2026-05-08 15:20

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_job_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Raw uploaded file (local storage fallback when no cloud bucket is set).', null=True, upload_to=jobs.models._resume_upload_path),
        ),
        migrations.AddField(
            model_name='document',
            name='is_master',
            field=models.BooleanField(db_index=True, default=False, help_text="True if this is the user's original uploaded Master Resume."),
        ),
    ]
