# Generated by Django 6.0.4 on 2026-05-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_add_document_is_master_and_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_content',
            field=models.JSONField(blank=True, help_text='AI-generated application content (tailored_bullets, cover_letter, form_fields).', null=True),
        ),
    ]
