# Generated by Django 6.0.4 on 2026-04-27 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text="Short professional headline (e.g. 'Senior Backend Engineer').", max_length=255)),
                ('location', models.CharField(blank=True, help_text='City, Country.', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('portfolio_url', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('experience', models.JSONField(blank=True, default=list, help_text='List of work experience objects.')),
                ('education', models.JSONField(blank=True, default=list, help_text='List of education objects.')),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skill objects with name and level.')),
                ('job_preferences', models.JSONField(blank=True, default=dict, help_text='Desired roles, locations, salary range, remote preference, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
