# Generated by Django 6.0.4 on 2026-05-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career_intelligence',
            field=models.JSONField(blank=True, default=dict, help_text='{years_experience, primary_domain, specializations} extracted from resume or set by user.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
