"""
Django settings for pathfind project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

import dj_database_url
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Base directory & .env loading
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env for local development; in production, vars come from the host env.
load_dotenv(BASE_DIR / ".env")

# ---------------------------------------------------------------------------
# Core security
# ---------------------------------------------------------------------------
SECRET_KEY = os.environ["SECRET_KEY"]

DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Production Security Settings
if not DEBUG:
    SECURE_SSL_REDIRECT = False  # Render handles HTTPS proxying; True causes internal health checks to hang
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = "DENY"
    # Trust reverse proxy (e.g. Heroku/AWS ALB/Render)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ---------------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------------
INSTALLED_APPS = [
    # Django built-ins
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",   # ArrayField for embedding vectors
    # Third-party
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt",
    "corsheaders",
    "storages",
    "django_celery_beat",
    # Local apps
    "accounts",
    "jobs",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",          # must be first
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pathfind.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pathfind.wsgi.application"

# ---------------------------------------------------------------------------
# Database
# Reads DATABASE_URL from the environment. Works for both local PostgreSQL
# and NeonDB.
# ---------------------------------------------------------------------------
db_config = dj_database_url.config(
    env="DATABASE_URL",
    # Best practice: 0 when using an external pooler (like Neon's PgBouncer)
    conn_max_age=0,
    conn_health_checks=True,
)

DATABASES = {
    "default": db_config
}

# ---------------------------------------------------------------------------
# Custom User model
# ---------------------------------------------------------------------------
AUTH_USER_MODEL = "accounts.User"

# ---------------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ---------------------------------------------------------------------------
# Internationalisation
# ---------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ---------------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------------
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
    },
}

# ---------------------------------------------------------------------------
# DRF Spectacular (Swagger/OpenAPI)
# ---------------------------------------------------------------------------
SPECTACULAR_SETTINGS = {
    "TITLE": "Pathfind API",
    "DESCRIPTION": "API Documentation for Pathfind, an AI-driven job curation platform.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True, # Useful for separate request/response schemas
}

# ---------------------------------------------------------------------------
# JWT (SimpleJWT)
# ---------------------------------------------------------------------------
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# ---------------------------------------------------------------------------
# CORS  (allow Next.js dev server + any additional origins from env)
# ---------------------------------------------------------------------------
_cors_origins = os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000")
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(",") if o.strip()]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

# ---------------------------------------------------------------------------
# Google OAuth 2.0
# ---------------------------------------------------------------------------
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET", "")

# ---------------------------------------------------------------------------
# AWS S3 — Document / file storage (django-storages + boto3)
#
# All variables are read from the environment so you can swap between
# LocalFileSystem (dev) and S3 (staging/prod) without touching this file.
#
# Required env vars for S3 to be active:
#   USE_S3=True
#   AWS_ACCESS_KEY_ID
#   AWS_SECRET_ACCESS_KEY
#   AWS_STORAGE_BUCKET_NAME
#   AWS_S3_REGION_NAME          (e.g. us-east-1)
#
# Optional:
#   AWS_S3_CUSTOM_DOMAIN        (CloudFront CDN domain, without https://)
#   AWS_PRESIGNED_EXPIRY        (seconds, default 3600)
# ---------------------------------------------------------------------------
USE_S3 = os.getenv("USE_S3", "False") == "True"

if USE_S3:
    # Credentials
    AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
    AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]
    AWS_STORAGE_BUCKET_NAME = os.environ["AWS_STORAGE_BUCKET_NAME"]
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")

    # Security: do not allow public ACL — serve via presigned URLs instead
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = True  # presigned URLs
    AWS_QUERYSTRING_EXPIRE = int(os.getenv("AWS_PRESIGNED_EXPIRY", "3600"))  # 1 hour

    # Optional CDN domain (CloudFront)
    _cdn_domain = os.getenv("AWS_S3_CUSTOM_DOMAIN", "")
    if _cdn_domain:
        AWS_S3_CUSTOM_DOMAIN = _cdn_domain

    # Use S3 for all user-uploaded media files.
    # Django 4.2+ storages() syntax:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
                "default_acl": AWS_DEFAULT_ACL,
                "file_overwrite": AWS_S3_FILE_OVERWRITE,
                "querystring_auth": AWS_QUERYSTRING_AUTH,
                "querystring_expire": AWS_QUERYSTRING_EXPIRE,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/"
else:
    # Local development: serve media from MEDIA_ROOT
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"


# ---------------------------------------------------------------------------
# Celery — task queue & scheduled jobs
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://localhost:6379/0")

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Route user-facing, latency-sensitive tasks to a dedicated high-priority queue
CELERY_TASK_ROUTES = {
    'jobs.tasks.ingestion.parse_resume_task': {'queue': 'high_priority'},
    'jobs.tasks.ingestion.generate_application_content_task': {'queue': 'high_priority'},
    'jobs.submit_to_portal': {'queue': 'high_priority'},
}

# Use django_celery_beat's DB-backed scheduler so beat can be managed via admin.
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Periodic task schedule: fetch from each job-board API every 8 hours.
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    "fetch-adzuna-jobs-every-8h": {
        "task": "jobs.fetch_adzuna_jobs",
        "schedule": crontab(minute=0, hour="*/8"),
    },
    "fetch-jooble-jobs-every-8h": {
        "task": "jobs.fetch_jooble_jobs",
        "schedule": crontab(minute=15, hour="*/8"),  # offset by 15 min to spread load
    },
    "fetch-careerjet-jobs-every-8h": {
        "task": "jobs.fetch_careerjet_jobs",
        "schedule": crontab(minute=30, hour="*/8"),  # offset by 30 min to spread load
    },
    # Nightly back-fill: encode any job listings that slipped through the
    # post-save signal (e.g. bulk inserts from the ingestion pipeline).
    "recompute-missing-embeddings-daily": {
        "task": "jobs.recompute_all_embeddings",
        "schedule": crontab(minute=0, hour=3),  # 3 AM UTC
    },
    "cleanup-old-jobs-daily": {
        "task": "jobs.cleanup_old_jobs",
        "schedule": crontab(minute=0, hour=4),  # 4 AM UTC
    },
}

# ---------------------------------------------------------------------------
# Django Cache — used by CuratedFeedView to store per-user profile vectors
# and avoid redundant SBERT inference on every request.
#
# Production: uses Redis (same instance as Celery broker, zero extra infra).
# Development: falls back to LocMemCache.
# ---------------------------------------------------------------------------

# Explicit toggle to activate Redis. Defaults to False for local development.
USE_REDIS = os.getenv("USE_REDIS", "False").lower() == "true"

if USE_REDIS:
    # Grabs the internal connection string you pasted into your environment variables
    _redis_url = os.getenv("REDIS_URL", "redis://localhost:6379/0")
    
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": _redis_url,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                # Pickle serialiser preserves numpy arrays correctly.
                "SERIALIZER": "django_redis.serializers.pickle.PickleSerializer",
            },
            "KEY_PREFIX": "pathfind",
            "TIMEOUT": 3600,  # default TTL: 1 hour
        }
    }
else:
    # Fallback for local development environments
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "pathfind-default",
        }
    }

# ---------------------------------------------------------------------------
# Job-board API credentials
# (leave blank in .env until you obtain the keys — providers are skipped
#  gracefully when their keys are missing)
# ---------------------------------------------------------------------------

# Adzuna — https://developer.adzuna.com/
ADZUNA_APP_ID = os.getenv("ADZUNA_APP_ID", "")
ADZUNA_APP_KEY = os.getenv("ADZUNA_APP_KEY", "")
ADZUNA_COUNTRY = os.getenv("ADZUNA_COUNTRY", "gb")  # ISO 3166-1 alpha-2

# Jooble — https://jooble.org/api/about
JOOBLE_API_KEY = os.getenv("JOOBLE_API_KEY", "")

# Careerjet — https://www.careerjet.com/partners/api/
CAREERJET_AFFID = os.getenv("CAREERJET_AFFID", "")
CAREERJET_LOCALE = os.getenv("CAREERJET_LOCALE", "en_GB")

# ---------------------------------------------------------------------------
# Semantic Matching — Sentence-BERT embedding model
# ---------------------------------------------------------------------------
# Model identifier passed to SentenceTransformer().
# "all-MiniLM-L6-v2" is a fast, high-quality 384-dim model (~80 MB).
# Swap for "all-mpnet-base-v2" (768-dim) if you need higher accuracy and
# can afford the 2x inference latency.
EMBEDDING_MODEL_NAME = os.getenv("EMBEDDING_MODEL_NAME", "all-MiniLM-L6-v2")

# ---------------------------------------------------------------------------
# Google Generative AI (Gemini)
# ---------------------------------------------------------------------------
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# ---------------------------------------------------------------------------
# Browserbase — remote browser sessions for portal auto-submission
# ---------------------------------------------------------------------------
# Sign up at https://browserbase.com to obtain these credentials.
# Required by jobs.tasks.portal_submission.submit_to_portal_task
BROWSERBASE_API_KEY    = os.getenv("BROWSERBASE_API_KEY", "")
BROWSERBASE_PROJECT_ID = os.getenv("BROWSERBASE_PROJECT_ID", "")

# ---------------------------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}
